// <auto-generated />
using System;
using ArchitecturalDreamMachineBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchitecturalDreamMachineBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ArchitecturalDreamMachineBackend.Data.Design", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("LotSize")
                        .HasColumnType("REAL");

                    b.Property<string>("StyleKeywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("ArchitecturalDreamMachineBackend.Data.StyleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("EavesOverhang")
                        .HasColumnType("REAL");

                    b.Property<string>("ExteriorMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoundationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEaves")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParapet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RoofPitch")
                        .HasColumnType("REAL");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TypicalCeilingHeight")
                        .HasColumnType("REAL");

                    b.Property<int>("TypicalStories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WindowStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WindowToWallRatio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StyleTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingShape = "rectangular",
                            Color = "gray",
                            EavesOverhang = 0.0,
                            ExteriorMaterial = "concrete",
                            FoundationType = "slab",
                            HasEaves = false,
                            HasParapet = true,
                            Name = "Brutalist",
                            RoofPitch = 0.0,
                            RoofType = "flat",
                            RoomCount = 4,
                            Texture = "concrete",
                            TypicalCeilingHeight = 12.0,
                            TypicalStories = 1,
                            WindowStyle = "small",
                            WindowToWallRatio = 0.10000000000000001
                        },
                        new
                        {
                            Id = 2,
                            BuildingShape = "l-shape",
                            Color = "cream",
                            EavesOverhang = 2.0,
                            ExteriorMaterial = "wood siding",
                            FoundationType = "crawlspace",
                            HasEaves = true,
                            HasParapet = false,
                            Name = "Victorian",
                            RoofPitch = 8.0,
                            RoofType = "gabled",
                            RoomCount = 6,
                            Texture = "wood",
                            TypicalCeilingHeight = 9.0,
                            TypicalStories = 2,
                            WindowStyle = "ornate",
                            WindowToWallRatio = 0.20000000000000001
                        },
                        new
                        {
                            Id = 3,
                            BuildingShape = "rectangular",
                            Color = "white",
                            EavesOverhang = 0.0,
                            ExteriorMaterial = "stucco",
                            FoundationType = "slab",
                            HasEaves = false,
                            HasParapet = true,
                            Name = "Modern",
                            RoofPitch = 0.0,
                            RoofType = "flat",
                            RoomCount = 5,
                            Texture = "glass",
                            TypicalCeilingHeight = 10.0,
                            TypicalStories = 2,
                            WindowStyle = "large",
                            WindowToWallRatio = 0.29999999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
